
- hosts: All
  tasks:
    - name: Creates a cron job
      cron:
        name: yum autoupdate servers
        weekday: "*"
        minute: "*"
        hour: "*"
        day: "1"
        month: "*"
        user: ec2-user
        job: "yum update -y" or "apt update -y"      
      when: "ansible_os_family == 'RedHat' or ansible_distribution == 'Amazon' or ansible_os_family == 'Debian'"
